### ISSUE TITLE
Tag versions

### ISSUE THREAD

**Issue by abremges** [metagenomics/2015-biogas-cebitec#16]
I might suggest putting a tag on the repo so that you can link to the last time you actually ran the Docker container.

**Comment by abremges** [comment]
Using DockerHub's automated builds, this is not a straightforward thing to do.
One solution is to have an orphan branch with the latest tested version, but this is rather ugly.

As we (hopefully) fixed any Docker problems now, I don't see the need for this "finished" project.
@pbelmann Let's just make sure that everything runs smoothly before we resubmit - closing this.

**Comment by abremges** [comment]
Actually, after discussing this with @asczyrba, I introduced the requested tags:
https://github.com/metagenomics/2015-biogas-cebitec/releases

The Docker container will still be updated if we push to the master branch.
But one can rebuild the container by loading the Dockerfile of any release.

**Comment by pbelmann** [comment]
We could try to switch to quay.io
It allows git tag -> docker tag  tracking

See jpilloras answer to my question:
https://github.com/docker/docker/issues/9561

**Comment by abremges** [comment]
Cool feature & definitely useful, e.g. for shipping bioboxes and stuff.

However, I don't see the real practical benefit for this project.
If the container works, there is no interest to re-run an earlier version.
Therefore, I'd leave it on DockerHub (also for longevity reasons).

**Comment by pbelmann** [comment]
I agree. 
For future development of this pipeline we should think about it since quay.io allows direct conversion to rkt.
