### ISSUE TITLE
Example: Docker on AWS

### ISSUE THREAD

**Issue by abremges** [metagenomics/2015-biogas-cebitec#21]
Add missing information to README:
- Specify minimum requirements (CPUs, RAM, storage) to run it on Amazon's EC2 instances
- Take care of special requirements (reformatting any volumes? mount stuff?)

Co-assigning myself (why can't I assign 2 people? Pff).

**Comment by abremges** [comment]
Ultimate goal for README:
- step-by-step guide

**Comment by abremges** [comment]
@pbelmann Are there any more steps we need to describe, to guide people how to run in on an EC2 instance? We should at least state memory and storage requirements, and possibly even provide a detailed walkthrough.

**Comment by pbelmann** [comment]
max HDD 82.55448 GB
max MEM 134.3495 GB

I try build a plot out of my log data for memory consumption.
I will provide a PR for the guide.

**Comment by abremges** [comment]
Perfect, thanks! :+1:

**Comment by pbelmann** [comment]
The mem value was retrieved by using cAdvisor.
CAdvisor returns a value that is composed of cached disk space as well as used space.
This is correct but can lead to a misunderstanding as stated in this issue: https://github.com/docker/docker/issues/10824

The value (used space - cache) for this pipeline is: 88.95996 GB .
