### ISSUE TITLE
Docker Automated Build with tag not working with Bitbucket

### ISSUE THREAD

**Issue by ntquyen** [metagenomics/2015-biogas-cebitec#41]
I have setup Docker automated build to linked with my private Bitbucket repo and try to trigger the build with default setting as "Branch". It works fine, even with automatically trigger by pushing changes to Bitbucket. But it doesn't work with tag. It doesn't trigger when I pushed a tag to Biubucket. Below is what I did:
1. In Docker Hub repo, tab "Build Details",  Tag Name set as `/^[0-9.]+$/` and Docker Tag Name set as `release-{sourceref}`. Saved.
2. Push tag changes:

```
$ git tag -a 1.0.1 -m "new tag 1.0.1"
$ git push --follow-tags
```

At this step, the build must have been triggered, but it wasn't.

One more notice, when I linked docker hub repo with Bitbucket repo, the link `https://registry.hub.docker.com/hooks/bitbucket` wasn't added automatically as it should be according to the docs https://docs.docker.com/docker-hub/bitbucket/. I had to add it manually to work with "Branch" build.

**Comment by abremges** [comment]
How is your issue related to this repository?
Did you base your Dockerfile on ours? /A

**Comment by ntquyen** [comment]
Oh, I'm sorry, I posted to a wrong place!
